// Create nodes for entities
CREATE (Iran:GPE {val: "Iran"})
CREATE (Israel:GPE {val: "Israel"})
CREATE (Tehran:GPE {val: "Tehran"})
CREATE (Tel_Aviv:GPE {val: "Tel Aviv"})
CREATE (Jerusalem:GPE {val: "Jerusalem"})
CREATE (Gaza:GPE {val: "Gaza"})
CREATE (Lebanon:GPE {val: "Lebanon"})
CREATE (West_Bank:GPE {val: "West Bank"})
CREATE (HaKirya:LOC {val: "HaKirya"})
CREATE (Dimona:GPE {val: "Dimona"})
CREATE (Fordow:FAC {val: "Fordow"})
CREATE (Natanz:FAC {val: "Natanz"})
CREATE (Semnan_Province:GPE {val: "Semnan Province"})
CREATE (United_States:GPE {val: "United States"})
CREATE (Washington:GPE {val: "Washington"})
CREATE (Russia:GPE {val: "Russia"})
CREATE (China:GPE {val: "China"})
CREATE (Saudi_Arabia:GPE {val: "Saudi Arabia"})
CREATE (Riyadh:GPE {val: "Riyadh"})
CREATE (Egypt:GPE {val: "Egypt"})
CREATE (Oman:GPE {val: "Oman"})
CREATE (Muscat:GPE {val: "Muscat"})
CREATE (United_Kingdom:GPE {val: "United Kingdom"})
CREATE (France:GPE {val: "France"})
CREATE (Germany:GPE {val: "Germany"})
CREATE (Europe:LOC {val: "Europe"})
CREATE (Middle_East:LOC {val: "Middle East"})
CREATE (Yemen:GPE {val: "Yemen"})
CREATE (Syria:GPE {val: "Syria"})
CREATE (Iraq:GPE {val: "Iraq"})
CREATE (Ardabil:GPE {val: "Ardabil"})
CREATE (Kerman:GPE {val: "Kerman"})
CREATE (Shahid_Rajaee:GPE {val: "Shahid Rajaee"})
CREATE (Lavisan_Shian:GPE {val: "Lavisan-Shian"})
CREATE (Varamin:GPE {val: "Varamin"})
CREATE (Turquzabad:GPE {val: "Turquzabad"})
CREATE (UAE:GPE {val: "UAE"})
CREATE (Hong_Kong:GPE {val: "Hong Kong"})
CREATE (Beirut:GPE {val: "Beirut"})
CREATE (Vienna:GPE {val: "Vienna"})
CREATE (Oslo:GPE {val: "Oslo"})

CREATE (Jun_08:DATE {val: "Jun. 08"})
CREATE (Jun_10:DATE {val: "Jun. 10"})
CREATE (Jun_11:DATE {val: "Jun. 11"})
CREATE (June_7:DATE {val: "June 7"})
CREATE (Sunday_June_15:DATE {val: "Sunday, June 15"})
CREATE (October_2024:DATE {val: "October 2024"})
CREATE (October_24_2024:DATE {val: "October 24, 2024"})
CREATE (October_7_2023:DATE {val: "October 7, 2023"})
CREATE (April_17:DATE {val: "April 17"})
CREATE (d2015:DATE {val: "2015"})
CREATE (d2018:DATE {val: "2018"})
CREATE (d2019:DATE {val: "2019"})
CREATE (d2023:DATE {val: "2023"})
CREATE (d2003:DATE {val: "2003"})
CREATE (last_week:DATE {val: "last week"})
CREATE (recent_months:DATE {val: "recent months"})
CREATE (early_2000s:DATE {val: "the early 2000s"})
CREATE (past_two_years:DATE {val: "the past two years"})
CREATE (coming_weeks:DATE {val: "the coming weeks"})
CREATE (August:DATE {val: "August"})
CREATE (October_18:DATE {val: "October 18"})

CREATE (Operation_Al_Aqsa_Storm:EVENT {val: "Operation Al-Aqsa Storm"})
CREATE (Battle_of_Shadows:EVENT {val: "the Battle of Shadows"})
CREATE (Eid_al_Adha:EVENT {val: "Eid al-Adha"})
CREATE (Oslo_Forum:EVENT {val: "the Oslo Forum"})

CREATE (IRIB:ORG {val: "Islamic Republic of Iran Broadcasting"})
CREATE (Intelligence_Ministry:ORG {val: "Intelligence Ministry"})
CREATE (Mossad:ORG {val: "Mossad"})
CREATE (Shin_Bet:ORG {val: "Shin Bet"})
CREATE (Aman:ORG {val: "Aman"})
CREATE (IAEA:ORG {val: "International Atomic Energy Agency"})
CREATE (IRGC:ORG {val: "Islamic Revolutionary Guard Corps"})
CREATE (SNSC:ORG {val: "Supreme National Security Council"})
CREATE (Hamas:ORG {val: "Hamas"})
CREATE (Hezbollah:ORG {val: "Hezbollah"})
CREATE (Houthis:ORG {val: "Houthis"})
CREATE (AEOI:ORG {val: "Atomic Energy Organization of Iran"})
CREATE (NPT:ORG {val: "NPT"})
CREATE (JCPOA:ORG {val: "JCPOA"})
CREATE (UN:ORG {val: "United Nations"})
CREATE (UNSC:ORG {val: "UN Security Council"})
CREATE (CENTCOM:ORG {val: "United States Central Command"})
CREATE (CIA:ORG {val: "CIA"})
CREATE (IDF:ORG {val: "IDF"})
CREATE (Mehr_News_Agency:ORG {val: "Mehr News Agency"})
CREATE (IRNA:ORG {val: "IRNA"})
CREATE (Tasnim_News_Agency:ORG {val: "Tasnim News Agency"})
CREATE (al_Mayadeen:ORG {val: "al-Mayadeen"})
CREATE (Israel_Hayom:ORG {val: "Israel Hayom"})
CREATE (Channel_12:ORG {val: "Channel 12"})
CREATE (Walla:ORG {val: "Walla"})
CREATE (Maariv:ORG {val: "Maariv"})
CREATE (BBC_Persian:ORG {val: "BBC Persian"})
CREATE (Reuters:ORG {val: "Reuters"})
CREATE (Jerusalem_Post:ORG {val: "The Jerusalem Post"})
CREATE (Financial_Times:ORG {val: "The Financial Times"})
CREATE (New_York_Post:ORG {val: "New York Post"})
CREATE (Wall_Street_Journal:ORG {val: "Wall Street Journal"})
CREATE (Treasury_Department:ORG {val: "US Treasury Department"})
CREATE (Pishgaman_Tejarat_Rafi_Novin_Co:ORG {val: "Pishgaman Tejarat Rafi Novin Co."})
CREATE (Lion_Commodities_Holdings_Ltd:ORG {val: "Lion Commodities Holdings Ltd."})
CREATE (Axis_of_Resistance:ORG {val: "Axis of Resistance"})
CREATE (NCRI:ORG {val: "National Council of Resistance of Iran"})

CREATE (Iranian:NORP {val: "Iranian"})
CREATE (Israeli:NORP {val: "Israeli"})
CREATE (Zionist:NORP {val: "Zionist"})
CREATE (Palestinian:NORP {val: "Palestinian"})
CREATE (American:NORP {val: "American"})
CREATE (European:NORP {val: "European"})
CREATE (Saudi:NORP {val: "Saudi"})
CREATE (Egyptian:NORP {val: "Egyptian"})
CREATE (Houthi:NORP {val: "Houthi"})
CREATE (Shiite:NORP {val: "Shi'ite"})
CREATE (Sunni:NORP {val: "Sunni"})
CREATE (Islamic:NORP {val: "Islamic"})

CREATE (Esmaeil_Khatib:PERSON {val: "Esmaeil Khatib"})
CREATE (Abbas_Araghchi:PERSON {val: "Abbas Araghchi"})
CREATE (Ali_Khamenei:PERSON {val: "Ali Khamenei"})
CREATE (Masoud_Pezeshkian:PERSON {val: "Masoud Pezeshkian"})
CREATE (Mohsen_Rezaei:PERSON {val: "Mohsen Rezaei"})
CREATE (Habibollah_Sayyari:PERSON {val: "Habibollah Sayyari"})
CREATE (Rafael_Grossi:PERSON {val: "Rafael Grossi"})
CREATE (Donald_Trump:PERSON {val: "Donald Trump"})
CREATE (Benjamin_Netanyahu:PERSON {val: "Benjamin Netanyahu"})
CREATE (Steve_Witkoff:PERSON {val: "Steve Witkoff"})
CREATE (Marco_Rubio:PERSON {val: "Marco Rubio"})
CREATE (Michael_Kurilla:PERSON {val: "Michael Kurilla"})
CREATE (Pete_Hegseth:PERSON {val: "Pete Hegseth"})
CREATE (Khalid_bin_Salman:PERSON {val: "Khalid bin Salman"})
CREATE (Salman_bin_Abdulaziz:PERSON {val: "Salman bin Abdulaziz"})
CREATE (Abdel_Fattah_el_Sisi:PERSON {val: "Abdel Fattah el-Sisi"})
CREATE (Badr_Abdelatt:PERSON {val: "Badr Abdelatt"})
CREATE (Hossein_Shanbehzadeh:PERSON {val: "Hossein Shanbehzadeh"})
CREATE (Mohsen_Langarneshin:PERSON {val: "Mohsen Langarneshin"})
CREATE (Qassem_Soleimani:PERSON {val: "Qassem Soleimani"})
CREATE (Hassan_Nasrallah:PERSON {val: "Hassan Nasrallah"})
CREATE (Yahya_Sinwar:PERSON {val: "Yahya Sinwar"})
CREATE (Mohammed_Sinwar:PERSON {val: "Mohammed Sinwar"})
CREATE (Ismail_Haniyeh:PERSON {val: "Ismail Haniyeh"})
CREATE (Fuad_Shukr:PERSON {val: "Fuad Shukr"})
CREATE (Ibrahim_Aqil:PERSON {val: "Ibrahim Aqil"})
CREATE (Mordechai_Vanunu:PERSON {val: "Mordechai Vanunu"})
CREATE (David_Barnea:PERSON {val: "David Barnea"})
CREATE (Wendy_Sherman:PERSON {val: "Wendy Sherman"})
CREATE (Esmaeil_Baqaei:PERSON {val: "Esmaeil Baqaei"})
CREATE (Behrouz_Kamalvandi:PERSON {val: "Behrouz Kamalvandi"})
CREATE (Sergei_Ryabkov:PERSON {val: "Sergei Ryabkov"})
CREATE (Mohammad_Bagheri:PERSON {val: "Mohammad Bagheri"})
CREATE (Reza_Salehi_Amiri:PERSON {val: "Reza Salehi Amiri"})
CREATE (Mohammed_bin_Zayed_Al_Nahyan:PERSON {val: "Mohammed bin Zayed Al Nahyan"})

// Relationships
// WHAT: Iran acquired sensitive Israeli documents
CREATE (Iran)-[:ACQUIRED {what: "sensitive documents"}]->(Israel)
CREATE (Intelligence_Ministry)-[:CONDUCTED {what: "intelligence operation"}]->(Israel)
CREATE (IRIB)-[:REPORTED {what: "document acquisition"}]->(Iran)
CREATE (SNSC)-[:CONFIRMED {what: "document acquisition"}]->(Iran)
CREATE (Esmaeil_Khatib)-[:DESCRIBED {what: "documents as treasure trove"}]->(Israel)
CREATE (Mohsen_Rezaei)-[:STATED {what: "no safe haven in Israel"}]->(Israel)

// WHY: Strategic advantage and retaliation capability
CREATE (Iran)-[:SEEKS {why: "strategic advantage"}]->(Israel)
CREATE (SNSC)-[:WARNED {why: "retaliation capability"}]->(Israel)
CREATE (Iran)-[:AIMS {why: "balance of power"}]->(Israel)
CREATE (Intelligence_Ministry)-[:UTILIZES {why: "enhance armed forces"}]->(Iran)

// WHO: Key individuals and organizations involved
CREATE (Esmaeil_Khatib)-[:LEADS]->(Intelligence_Ministry)
CREATE (Abbas_Araghchi)-[:NEGOTIATES]->(United_States)
CREATE (Ali_Khamenei)-[:REJECTS {who: "US nuclear proposal"}]->(United_States)
CREATE (Masoud_Pezeshkian)-[:PRESIDENT_OF]->(Iran)
CREATE (Rafael_Grossi)-[:DIRECTS]->(IAEA)
CREATE (Donald_Trump)-[:PRESIDENT_OF]->(United_States)
CREATE (Benjamin_Netanyahu)-[:PRIME_MINISTER_OF]->(Israel)
CREATE (Steve_Witkoff)-[:NEGOTIATES_FOR]->(United_States)
CREATE (Michael_Kurilla)-[:COMMANDS]->(CENTCOM)
CREATE (Khalid_bin_Salman)-[:DELIVERS_MESSAGE_FOR]->(Saudi_Arabia)
CREATE (Hossein_Shanbehzadeh)-[:ACCUSED_BY]->(Iran)

// WHERE: Locations of events and operations
CREATE (Intelligence_Ministry)-[:OPERATED_IN {where: "occupied territories"}]->(Israel)
CREATE (Iran)-[:TRANSFERRED_TO {where: "secure locations"}]->(Tehran)
CREATE (Mossad)-[:BASED_IN]->(HaKirya)
CREATE (Iran)-[:NEGOTIATES_IN]->(Muscat)
CREATE (Abbas_Araghchi)-[:VISITS]->(Oslo)
CREATE (Khalid_bin_Salman)-[:VISITED]->(Tehran)
CREATE (Hossein_Shanbehzadeh)-[:ARRESTED_IN]->(Ardabil)

// WHEN: Timing of events
CREATE (Iran)-[:ACQUIRED_ON {when: "Jun. 08"}]->(Jun_08)
CREATE (IRIB)-[:REPORTED_ON {when: "June 7"}]->(June_7)
CREATE (SNSC)-[:WARNED_ON {when: "Monday"}]->(Jun_10)
CREATE (Intelligence_Ministry)-[:STATEMENT_ON {when: "Tuesday"}]->(Jun_11)
CREATE (Iran)-[:NEGOTIATES_ON {when: "Sunday, June 15"}]->(Sunday_June_15)
CREATE (Israel)-[:DESTROYED_ON {when: "October 24, 2024"}]->(October_24_2024)
CREATE (Operation_Al_Aqsa_Storm)-[:OCCURRED_ON {when: "October 7, 2023"}]->(October_7_2023)

// HOW: Methods and strategies
CREATE (Intelligence_Ministry)-[:USED {how: "cyber and field operation"}]->(Israel)
CREATE (Iran)-[:NEGOTIATES_VIA {how: "indirect talks"}]->(Oman)
CREATE (Intelligence_Ministry)-[:EXFILTRATED {how: "multi-layered plan"}]->(Israel)
CREATE (Iran)-[:STRENGTHENS {how: "Axis of Resistance"}]->(Hamas)
CREATE (Iran)-[:STRENGTHENS {how: "Axis of Resistance"}]->(Hezbollah)
CREATE (Iran)-[:STRENGTHENS {how: "Axis of Resistance"}]->(Houthis)
CREATE (Iran)-[:ORDERS {how: "missile ingredients from China"}]->(China)

// Additional relationships for context
CREATE (IAEA)-[:INSPECTS]->(Iran)
CREATE (IAEA)-[:REPORTS_ON {when: "recent months"}]->(recent_months)
CREATE (Iran)-[:VIOLATES]->(NPT)
CREATE (United_States)-[:SANCTIONS]->(Iran)
CREATE (Saudi_Arabia)-[:WARNS {when: "April 17"}]->(Iran)
CREATE (Russia)-[:OFFERS_HELP]->(Iran)
CREATE (Iran)-[:ENRICHES {what: "uranium"}]->(Fordow)
CREATE (Iran)-[:ENRICHES {what: "uranium"}]->(Natanz)
CREATE (Israel)-[:THREATENS]->(Iran)
CREATE (Mossad)-[:SEIZED {when: "2018"}]->(d2018)
CREATE (NCRI)-[:REVEALS {when: "Tuesday"}]->(Semnan_Province)

// Proxy and regional relationships
CREATE (Iran)-[:SUPPORTS]->(Hamas)
CREATE (Iran)-[:SUPPORTS]->(Hezbollah)
CREATE (Iran)-[:SUPPORTS]->(Houthis)
CREATE (Israel)-[:TARGETS]->(Hamas)
CREATE (Israel)-[:TARGETS]->(Hezbollah)
CREATE (Israel)-[:TARGETS]->(Houthis)
CREATE (Iran)-[:INFLUENCES]->(Yemen)
CREATE (Iran)-[:INFLUENCES]->(Lebanon)
CREATE (Iran)-[:INFLUENCES]->(Gaza)
CREATE (Iran)-[:INFLUENCES]->(Iraq)
CREATE (Iran)-[:INFLUENCES]->(Syria)

// Media reporting relationships
CREATE (Mehr_News_Agency)-[:REPORTED]->(Iran)
CREATE (IRNA)-[:REPORTED]->(Iran)
CREATE (Tasnim_News_Agency)-[:REPORTED]->(Iran)
CREATE (al_Mayadeen)-[:REPORTED]->(Iran)
CREATE (Israel_Hayom)-[:REPORTED]->(Israel)
CREATE (Channel_12)-[:REPORTED]->(Israel)
CREATE (Walla)-[:REPORTED]->(Israel)
CREATE (Maariv)-[:REPORTED]->(Israel)
CREATE (Jerusalem_Post)-[:REPORTED]->(Iran)
CREATE (Financial_Times)-[:INTERVIEWED]->(Rafael_Grossi)
CREATE (Wall_Street_Journal)-[:REPORTED]->(Iran)

// Sanction and diplomatic relationships
CREATE (United_States)-[:IMPOSES {what: "sanctions"}]->(Pishgaman_Tejarat_Rafi_Novin_Co)
CREATE (United_States)-[:IMPOSES {what: "sanctions"}]->(Lion_Commodities_Holdings_Ltd)
CREATE (United_Kingdom)-[:SANCTIONS]->(Israel)
CREATE (Canada)-[:SANCTIONS]->(Israel)
CREATE (Australia)-[:SANCTIONS]->(Israel)
CREATE (New_Zealand)-[:SANCTIONS]->(Israel)
CREATE (Norway)-[:SANCTIONS]->(Israel)
CREATE (Iran)-[:CONDEMNS]->(United_States)
CREATE (Iran)-[:SEEKS_TIES]->(Egypt)
CREATE (Iran)-[:SEEKS_TIES]->(UAE)
CREATE (Iran)-[:PARTICIPATES_IN {when: "Eid al-Adha"}]->(Eid_al_Adha)